mweibel/facebook.ex

lib/facebook/graph.ex

An error tuple is returned from hackney requests and must be inspected because a tuple does not implement the String.Chars protocol.
```elixir
06:45:59.184 [error] GenServer #PID<0.697.2> terminating
** (exit) an exception was raised:
** (Protocol.UndefinedError) protocol String.Chars not implemented for {:error, :closed}
(elixir) lib/string/chars.ex:3: String.Chars.impl_for!/1
(elixir) lib/string/chars.ex:17: String.Chars.to_string/1
(facebook) lib/facebook/graph.ex:71: Facebook.Graph.request/4
(tu_account) lib/tu_account/facebook.ex:8: TUAccount.Facebook.fetch_facebook_id/1
(tu_account) lib/tu_account/dispatcher.ex:34: TUAccount.Dispatcher.handle_message/1
(tu_net) lib/tu_net/dispatcher/worker.ex:69: TUNet.Dispatcher.Worker.handle_message/2
(stdlib) timer.erl:194: :timer.tc/3
(tu_net) …
```

Fix crash on request failure cases

---

lib/facebook.ex
lib/facebook/graph.ex
mix.exs
test/facebook_test.exs

The problem with the 0.3.2 version of json package is that it raises an exception when trying to decode emojis, that turns out, are very common in Facebook posts and comments. The version 0.3.3 has this error fixed. I hope you can merge this soon, thank you!
I also changed the tab indentation to spaces as recommended in the elixir style guides. an Finally I bumped the version of this package.

Updating version of json package, with a resolved bug

---

lib/facebook.ex

I wrote a couple of functions to retrieve the **feed from a page**.
These functions are:
- _pageFeed/2_. Gets a maximum of 25 posts
- _pageFeed/3_. Gets a maximum of 100 posts
I am currently working on a function that fetches all the posts from a page, this could increment the limit of the retrieved posts.

Add function for page feed fetching

---

lib/facebook.ex

**Pull request fixed!**
I wrote a function to get the total number of people who liked an object.
An "object" stands for: post, comment, link, status update, photo and so on.
This function is: objectLikes/2
The object is searched by its id and then the number of likes is retrieved.

Fixed: Object likes

---

lib/facebook.ex

I have enhanced the pageFeed function.
Now you can pass the type of feed you want to get:
```
iex> Facebook.pageFeed(:posts, "CocaColaMx", "<Your Token>")
iex> Facebook.pageFeed(:tagged, "CocaColaMx", "<Your Token>", 55)
iex> Facebook.pageFeed(:promotable_posts, "CocaColaMx", "<Your Token>")
iex> Facebook.pageFeed(:feed, "CocaColaMx", "<Your Token>", 55, "id,name,actions")
```
All of this according to the [Graph API](https://developers.facebook.com/docs/graph-api/reference/v2.6/page/feed).

pageFeed enhanced!

---

lib/facebook.ex

I added a function to count how many times a given reaction appears on a post.
This function is: `objectCount/4`.
```
iex> Facebook.objectCount(:reaction, :wow, "769860109692136_1173416799336463", "<Token>")
2
iex> Facebook.objectCount(:reaction, :haha, "769860109692136_1173416799336463", "<Token>")
12
iex> Facebook.objectCount(:reaction, :thankful, "769860109692136_1173416799336463", "<Token>")
33
```
Additionally, I fixed a couple of issues in objectCount/3 and its related functions.

Object reactions

---

lib/facebook.ex

I was trying to use this wrapper to get data from facebook on a Ember + Phoenix stack and I figured out that Ember only handles the authorization on Facebook. We have to handle the authentication (using the authorizationCode) on the server side (phoenix).
I've added a function on your facebook module that handles it. 
Hope it will get merged.

get the access token from a authorization code

---

mix.exs

Update `mix.exs` to add `()` to the end of function calls

fix elixir 1.4 ambiguity warning message

---

lib/facebook.ex

I was using this package to get data from the FB Graph API and I noticed it didn't have a long lived access token creation method, so I added one.

Add request to get long lived access token

---

lib/facebook/graph.ex

It's just a suggestion, but I think the logger info level is too high, specially if you use Phoenix and facebook.ex in the same application.

Change logger level to debug

---

lib/facebook/stream.ex

Facebook error responses weren't handled correctly, which causes stream to fail

Fix bug on facebook error response.

---

lib/facebook/graph.ex

`:hackney.body(client_ref)` can return `{:ok, body}` or `{:error, reason}`, so I edited the code a little in order to manage both cases.

Capture hackney error

---

mix.exs

This commit bumps the graph_url to v2.9, the current API version.

Bump Facebook API version to 2.9

---

lib/facebook.ex
lib/facebook/graph.ex
test/facebook_test.exs

Didn't see any publishing functionality provided by the main `Facebook` module so figured I'd share this.
Coverage for most use cases is pretty good provided you know which fields to pass, adding a few more examples may help increase awareness to whats available (scheduling post datetime, setting post as unpublished are some examples), for now the facebook documentation is referenced in the doc.

Add publish to feed

---

lib/facebook.ex

[Facebook's debug token endpoint](https://developers.facebook.com/docs/graph-api/reference/v2.11/debug_token) allow developers to debug access tokens and receive useful data. 
**Changes**:
* New function `debug_token/2` was added

Support the token debugging

---

README.md
mix.exs

Added configuration documentation

Configuration documentation

---

lib/facebook.ex
test/facebook_test.exs

Just following: https://github.com/mweibel/facebook.ex/pull/62
Now it has the same name function with one more parameter.

Add custom dimension picture function

---

lib/facebook/graph_api.ex

Hi, 
I was playing around with fetching all available data from Facebook using Facebook.Stream.new, and came across this issue. I found it was failing with HTTPoison's `:nxdomain` error, and found `Facebook.Stream` wasing using `Facebook.GraphAPI`, which has  this function:
```
def process_url(url), do: Config.graph_url <> url
```
It attaches the graph endpoint url for all outgoing calls.
This wouldn't work for stream since the next page already comes with complete url:
```
https://graph.facebook.com/v3.1/260154614531202/live_videos?access_token=<access_token>&limit=25&after=QVFIUl9Bbnd2aTdSZAUhOWGp6ZA1ZA6aER3dk52ZATBCcGdILXlrUTIxenpQWGpuUFE5NnJDZAWVUYjZA3XzAxT1hZAdmlId1dhb0JTZAERqWWNrTnNqRjdKWGhsOTdR
```
This PR opts in to match if url contains protocol, if it does, use the url as is.
It …

Use the exact url in the pagination response

---

mix.exs
test/facebook_test.exs

Upgrade HTTPoison to <~ 1.4.0 and upgrade all other development deps

---

.formatter.exs
.travis.yml
lib/facebook.ex
lib/facebook/config.ex
lib/facebook/graph_video_api.ex
lib/facebook/stream.ex
mix.exs
test/facebook_test.exs
test/graph_mock.ex

I wanted to add pull request with a new feature but auto code formatting makes diff unreadable. So, I decided to configure and run formatter in a separate PR. There are no other changes except formatter configuration and newer Elixir/OTP versions in Travis config.

Configure and run formatter

---

README.md
lib/facebook.ex
lib/facebook/config.ex
lib/facebook/graph_api.ex
mix.exs
test/facebook/config_test.exs
test/facebook_test.exs

Compile-time configuration doesn't work well with OTP releases, so I added runtime configuration support for all config keys.

Add support for runtime configuration via {:system, _} tuples

---

lib/facebook.ex
test/facebook_test.exs

I've ran a Dialyzer and found out that typespecs are messed up and similar functions use different conventions for fields (mostly it is a string with comma separated values but sometimes it is a list of strings).
I updated typepecs and unified fields usage.

Fix Dialyzer issues 
